# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  movie_service:
      class: AppBundle\Services\Entity\MovieService
      arguments: ["@doctrine"]

  rating_service:
      class: AppBundle\Services\Entity\RatingService
      arguments: ["@doctrine"]

  password_helper:
      class: AppBundle\Services\Security\PasswordHelper
      arguments: ["@security.encoder_factory"]
